# Generated by Django 3.2.6 on 2021-08-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='creat_todo_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_date', models.CharField(max_length=50)),
                ('todo_start_time', models.TimeField()),
                ('todo_end_time', models.TimeField()),
                ('todo_all_time', models.CharField(max_length=50)),
                ('todo_price', models.FloatField()),
            ],
        ),
    ]
