# Generated by Django 3.2.6 on 2021-08-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creat_todo_models',
            name='todo_all_time',
            field=models.TimeField(),
        ),
    ]
