# Generated by Django 3.2.6 on 2021-08-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_todo', '0002_alter_creat_todo_models_todo_all_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creat_todo_models',
            name='todo_all_time',
            field=models.CharField(max_length=50),
        ),
    ]
