# Generated by Django 3.2.6 on 2021-08-12 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money_todo', '0003_alter_creat_todo_models_todo_all_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creat_todo_models',
            name='todo_price',
        ),
    ]
