# Generated by Django 3.2.6 on 2021-08-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_todo', '0004_remove_creat_todo_models_todo_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='creat_todo_models',
            name='todo_day',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
    ]
